# Generated by Django 3.1.4 on 2021-03-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210312_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_urls',
            new_name='image_url',
        ),
    ]
