# Generated by Django 3.1.7 on 2021-03-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210312_0500'),
        ('user', '0002_auto_20210311_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
